[package]
name = "fedimint-wallet-tests"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-wallet-tests contains integration tests for the lightning module"
license = "MIT"
publish = false

[[test]]
name = "fedimint_wallet_tests"
path = "tests/tests.rs"

[[bin]]
name = "circular-deposit-test"
path = "src/bin/circular-deposit-test.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
devimint = { workspace = true }
fedimint-bitcoind = { path = "../../fedimint-bitcoind" }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-testing = { workspace = true }
fedimint-wallet-client = { path = "../fedimint-wallet-client" }
fedimint-wallet-common = { path = "../fedimint-wallet-common" }
fedimint-wallet-server = { path = "../fedimint-wallet-server" }
futures = { workspace = true }
rand = { workspace = true }
secp256k1 = { version = "0.27.0", features = [ "serde" ] }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fedimint-dummy-client = { path = "../fedimint-dummy-client", version = "=0.4.1-rc.0" }
fedimint-dummy-common = { path = "../fedimint-dummy-common", version = "=0.4.1-rc.0" }
fedimint-dummy-server = { path = "../fedimint-dummy-server", version = "=0.4.1-rc.0" }
