[package]
name = "fedimint-portalloc"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Port allocation utility for Fedimint"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_portalloc"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
dirs = "6.0.0"
fedimint-core = { workspace = true }
fs2 = "0.4.3"
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
