[package]
name = "fedimint-bitcoind"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Bitcoin Core connectivity used by Fedimint"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_bitcoind"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { version = "0.17.0", optional = true }
electrum-client = { version = "0.18.0", optional = true }
esplora-client = { workspace = true, optional = true }
fedimint-core  = { version = "=0.4.1", path = "../fedimint-core" }
fedimint-logging = { workspace = true }
hex = "0.4.3"
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[features]
default = ["bitcoincore-rpc", "electrum-client", "esplora-client"]
