[package]
name = "fedimint-derive-secret"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Fedimint derivable secret implementation"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_derive_secret"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin_hashes = { workspace = true }
bls12_381 = { workspace = true }
fedimint-core = { workspace = true }
hkdf = { workspace = true }
ring = { workspace = true }
