[package]
name = "fedimint-derive-secret"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Fedimint derivable secret implementation"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fedimint_derive_secret"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin_hashes = "0.11.0"
bls12_381 = { workspace = true }
fedimint-core = { workspace = true }
hkdf = { package = "fedimint-hkdf", version = "=0.4.2-rc.0", path = "../../crypto/hkdf" }
ring = "0.17.8"
secp256k1-zkp = { version = "0.9.2", features = [ "serde" ] }
