[package]
name = "fedimint-load-test-tool"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-load-test-tool is a tool to load test the fedimint server and gateway."
license = { workspace = true }
publish = false

[[bin]]
name = "fedimint-load-test-tool"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-wallet-client = { workspace = true }
futures = { workspace = true }
jsonrpsee-core = { version = "0.24.9", features = ["client"] }
lightning-invoice = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
tracing = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = { version = "0.24.9", default-features = false }
