services:
  fedimintd:
    image: fedimint/fedimintd:e06c9119cff03cbd541a2515218d96786edce6ef
    ports:
      - 8173:8173/tcp # p2p tls
      - 8173:8173/udp # p2p iroh
      - 8174:8174/udp # api iroh
      - 127.0.0.1:8175:8175/tcp # ui
    volumes:
      - fedimintd_data:/data
    environment:
      - FM_ENABLE_IROH=true
      - FM_BITCOIN_NETWORK=signet
      - FM_ESPLORA_URL=https://mutinynet.com/api
      - FM_BIND_P2P=0.0.0.0:8173
      - FM_BIND_API=0.0.0.0:8174
      - FM_BIND_UI=172.25.0.11:8175
    networks:
      fedimint_network:
        ipv4_address: 172.25.0.11
    restart: always

networks:
  fedimint_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

volumes:
  fedimintd_data:
