# Example audit config file
#
# It may be located in the user home (`~/.cargo/audit.toml`) or in the project
# root (`.cargo/audit.toml`).
#
# All of the options which can be passed via CLI arguments can also be
# permanently specified in this file.
#
#
# See the full example in: https://raw.githubusercontent.com/rustsec/rustsec/main/cargo-audit/audit.toml.example
[advisories]
ignore = [
  "RUSTSEC-2023-0052",
  "RUSTSEC-2023-0071",
  # we don't use borsch encoding
  "RUSTSEC-2024-0402",
  "RUSTSEC-2024-0370",
  "RUSTSEC-2024-0388",
  "RUSTSEC-2025-0006",
  # `instant` unmaintained
  "RUSTSEC-2024-0384",
  # ring has a panic that doesn't affect us
  "RUSTSEC-2025-0009",
  # ring has a panic that doesn't affect us
  "RUSTSEC-2025-0010",
  # `paste` unmaintained
  "RUSTSEC-2024-0436",
  # `backoff` unmaintained
  "RUSTSEC-2025-0012",
  # `protobuf` crash on untrusted data
  "RUSTSEC-2024-0437",
  # atomic-polyfill is unmaintained, waiting for the update chain to reach iroh
  "RUSTSEC-2023-0089",
]
