[package]
name = "fedimint-rocksdb"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-rocksdb provides a rocksdb-backed database implementation for Fedimint."
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_rocksdb"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
futures = { workspace = true }
rocksdb = { version = "0.22.0" }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3.15.0"

[target.'cfg(not(any(target_env = "msvc", target_os = "ios")))'.dependencies]
rocksdb = { version = "0.22.0", features = ["jemalloc"] }

[target.'cfg(not(target_family="wasm"))'.dependencies]
tokio = { workspace = true, features = [
  "rt",
  "rt-multi-thread",
  "sync",
  "time",
] }
