[package]
name = "fedimint-ln-server"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-ln is a lightning payment service module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_ln_server"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin_hashes = { package = "bitcoin_hashes", version = "0.12.0" }
erased-serde = { workspace = true }
fedimint-bitcoind = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-metrics = { workspace = true }
fedimint-server = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
threshold_crypto = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
test-log = { workspace = true }
