[package]
name = "fedimint-wallet-common"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-wallet-common is a n on-chain bitcoin wallet module. It uses a key-value store and is not a standard HD wallet. (common types)"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_wallet_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
fedimint-core = { workspace = true }
hex = { workspace = true }
impl-tools = "0.10.3"
miniscript = { workspace = true, features = ["serde"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }
