[package]
name = "fedimint-testing-core"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-testing provides a basic utils for testing fedimint components"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_testing_core"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-rocksdb = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
tempfile = "3.14.0"
tokio = { workspace = true }
tracing = { workspace = true }
